#!/usr/bin/env sh
set -e

if [ -f "/root/${APP_SUBDIRECTORY}/main.py" ]; then
    DEFAULT_MODULE_NAME=${APP_SUBDIRECTORY}.main
elif [ -f "/root/main.py" ]; then
    DEFAULT_MODULE_NAME=main
fi
PYTHON_MODULE_NAME=${PYTHON_MODULE_NAME:-$DEFAULT_MODULE_NAME}
PYTHON_VARIABLE_NAME=${PYTHON_VARIABLE_NAME:-app}
export PYTHON_APP=${PYTHON_APP:-"$PYTHON_MODULE_NAME:$PYTHON_VARIABLE_NAME"}

# if [ -f /root/${REQUIREMENTS_FILE} ]; then
#     DEFAULT_REQUIREMENTS_PATH=/root/${REQUIREMENTS_FILE}
# elif [ -f "/root/${APP_SUBDIRECTORY}/${REQUIREMENTS_FILE}" ]; then
#     DEFAULT_REQUIREMENTS_PATH=/root/${APP_SUBDIRECTORY}/${REQUIREMENTS_FILE}
# else
#     DEFAULT_REQUIREMENTS_PATH=/${REQUIREMENTS_FILE}
# fi
# export REQUIREMENTS_PATH=${REQUIREMENTS_PATH:-$DEFAULT_REQUIREMENTS_PATH}

if [ -f /root/${PREFLIGHT_FILE} ]; then
    DEFAULT_PREFLIGHT_PATH=/root/${PREFLIGHT_FILE}
elif [ -f "/root/${APP_SUBDIRECTORY}/${PREFLIGHT_FILE}" ]; then
    DEFAULT_PREFLIGHT_PATH=/root/${APP_SUBDIRECTORY}/${PREFLIGHT_FILE}
else
    DEFAULT_PREFLIGHT_PATH=/${PREFLIGHT_FILE}
fi
export PREFLIGHT_PATH=${PREFLIGHT_PATH:-$DEFAULT_PREFLIGHT_PATH}

if [ -f /root/${GUNICORN_CONF_FILE} ]; then
    DEFAULT_GUNICORN_CONF_PATH=/root/${GUNICORN_CONF_FILE}
elif [ -f "/root/${APP_SUBDIRECTORY}/${GUNICORN_CONF_FILE}" ]; then
    DEFAULT_GUNICORN_CONF_PATH=/root/${APP_SUBDIRECTORY}/${GUNICORN_CONF_FILE}
else
    DEFAULT_GUNICORN_CONF_PATH=/${GUNICORN_CONF_FILE}
fi
export GUNICORN_CONF_PATH=${GUNICORN_CONF_PATH:-$DEFAULT_GUNICORN_CONF_PATH}

exec "$@"