#!/usr/bin/env sh
set -e

if [ -f "/${BASE_NAME}/${APP_SUBDIRECTORY}/run.py" ]; then
    DEFAULT_PYTHON_MODULE=${APP_SUBDIRECTORY}.run
elif [ -f "/${BASE_NAME}/run.py" ]; then
    DEFAULT_PYTHON_MODULE=run
fi
PYTHON_MODULE_NAME=${PYTHON_MODULE_NAME:-$DEFAULT_PYTHON_MODULE}
PYTHON_VARIABLE_NAME=${PYTHON_VARIABLE_NAME:-app}
export PYTHON_APP=${PYTHON_APP:-"$PYTHON_MODULE_NAME:$PYTHON_VARIABLE_NAME"}

if [ -f "/${BASE_NAME}/${PREFLIGHT_FILE}" ]; then
    DEFAULT_PREFLIGHT_PATH=/${BASE_NAME}/${PREFLIGHT_FILE}
elif [ -f "/${BASE_NAME}/${APP_SUBDIRECTORY}/${PREFLIGHT_FILE}" ]; then
    DEFAULT_PREFLIGHT_PATH=/${BASE_NAME}/${APP_SUBDIRECTORY}/${PREFLIGHT_FILE}
else
    DEFAULT_PREFLIGHT_PATH=/${PREFLIGHT_FILE}
fi
export PREFLIGHT_PATH=${PREFLIGHT_PATH:-$DEFAULT_PREFLIGHT_PATH}

if [ -f "/${BASE_NAME}/${GUNICORN_CONF_FILE}" ]; then
    DEFAULT_GUNICORN_CONF_PATH=/${BASE_NAME}/${GUNICORN_CONF_FILE}
elif [ -f "/${BASE_NAME}/${APP_SUBDIRECTORY}/${GUNICORN_CONF_FILE}" ]; then
    DEFAULT_GUNICORN_CONF_PATH=/${BASE_NAME}/${APP_SUBDIRECTORY}/${GUNICORN_CONF_FILE}
else
    DEFAULT_GUNICORN_CONF_PATH=/${GUNICORN_CONF_FILE}
fi
export GUNICORN_CONF_PATH=${GUNICORN_CONF_PATH:-$DEFAULT_GUNICORN_CONF_PATH}

exec "$@"